---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

#rm(list=ls(all=TRUE))

```{r}
#Load the data from the csv file to a data frame
df <- read.csv('C:/Users/User/Desktop/SQL/Alex/My own version/June2023_CovidData.csv')

#Convert the date column into a time stamp
df$date <- as.POSIXct(df$date)

```


```{r}
# Compute summary statistics
#summary_df <- summary(df)
numeric_df <- df[, sapply(df, is.numeric)]

summary_table <- sapply(numeric_df, function(x) {
  c(Min = min(x, na.rm = TRUE),
    `1st Qu` = quantile(x, 0.25, na.rm = TRUE),
    Median = median(x, na.rm = TRUE),
    Mean = mean(x, na.rm = TRUE),
    `3rd Qu` = quantile(x, 0.75, na.rm = TRUE),
    Max = max(x, na.rm = TRUE))
})

t(summary_table)
#Need to color the table later to make it more readable
#https://cran.r-project.org/web/packages/colorDF/vignettes/colorDF.html
```
Compute the correlation matrix
Subset the data frame to include only numeric columns and replace NAs with 0

```{r}
numeric_df <- df[, sapply(df, is.numeric)]
numeric_df[is.na(numeric_df)] <- 0

# Compute the correlation matrix
corr <- cor(numeric_df)

# Set upper triangle values to NA
#corr[upper.tri(corr)] <- NA

#heatmap(corr, col = colorRampPalette(c("white", "orange", "red"))(100), symm = FALSE)

# Set upper triangle values to NA
corr[lower.tri(corr)] <- NA

# Create a triangular heatmap using upper triangle
heatmap(corr, col = colorRampPalette(c("white", "orange", "red"))(100), symm = FALSE, 
        Rowv = NA, Colv = NA, margins = c(10, 10))
```


```{r}
# Select relevant columns
selected_cols <- c(
  "total_cases", "new_cases", "new_deaths", "total_tests",
  "population_density", "median_age", "aged_65_older", "gdp_per_capita",
  "cardiovasc_death_rate", "diabetes_prevalence", "life_expectancy"
)

# Subset the dataframe with selected columns
subset_df <- numeric_df[names(numeric_df)]

# Calculate correlation matrix
cor_matrix <- cor(subset_df, use = "pairwise.complete.obs")

# Sort the correlations with total_cases in descending order
cor_with_total_cases <- cor_matrix[1, -1]

# Print the results
head(data.frame(sort(cor_with_total_cases, decreasing = TRUE)),10)

#Need to rename later
```
```{r}
# Install missing packages
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("maps")

library(ggplot2)
library(maps)
library(dplyr)

# Subset the relevant columns from the df dataset
world_map_data <- df[!(df$location %in% c("World","Europe","Africa","European Union","Low income","Lower middle income","North America","South Africa","South America"))
                     , c("location", "total_cases")]

# Merge with map data to get country borders
world_map <- map_data("world")


# Set the sample size (e.g., 10%)
sample_size <- 0.1

# Subset a random sample of rows from world_map_data
sample_data <- world_map_data %>%
  sample_n(size = round(nrow(.) * sample_size))

# Subset a random sample of rows from world_map
sample_map <- world_map %>%
  sample_n(size = round(nrow(.) * sample_size))

# Merge the sample datasets
merged_sample <- merge(sample_data, sample_map, by.x = "location", by.y = "region", all.x = TRUE)

# Check the resulting merged data
head(merged_sample)

# Merge map data with COVID-19 data
#merged_data <- merge(world_map_data, world_map, by.x = "location", by.y = "region", all.x = TRUE)

# Calculate the color intensity based on total_cases and total_deaths
merged_sample$color_intensity <- log10(merged_sample$total_cases + 1)


# Plot the world map
ggplot() +
  geom_map(data = merged_sample, map = sample_map, aes(x = long, y = lat, map_id = location, fill = color_intensity), 
           color = "grey", size = 0.2) +
  scale_fill_gradient(low = "lightgreen", high = "red", na.value = "white", guide = "legend") +
  theme_void() +
  labs(fill = "COVID-19 Cases (Log Scale)") +
  ggtitle("World COVID-19 Cases Map")

```

Tutorial with not ugly map: https://www.youtube.com/watch?v=AgWgPSZ7Gp0



```{r}
library(ggplot2)              #needs to be done each r session
library(tidyverse)            #needs to be done each r session

mapdata <- map_data("world") ##ggplot2
View(mapdata)
names(sample_data) = c("region","total_cases")

aggregated_data <- aggregate(total_cases ~ region, data = sample_data, FUN = max, na.rm = TRUE)

# Rename the aggregated column
colnames(aggregated_data)[2] <- "total_cases"

#mapdata <- left_join(mapdata, EUvax, by="region")
mapdata1 <- left_join(mapdata, aggregated_data, by = "region")
#mapdata0 <- merge(mapdata, sample_data, by = "region", all = FALSE)

mapdata2<-mapdata1 %>% filter(!is.na(mapdata1$total_cases))
View(mapdata2)

map1<-ggplot(mapdata2, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = total_cases), color = "black")
map1

map2 <- map1 + scale_fill_gradient(name = "cases", low = "yellow", high =  "red", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map2
```
Conclusions for the world part:...

###Continents
```{r}
library(dplyr)
library(ggplot2)

Avg_by_continent <- summarise(group_by(df, continent), 
                              total_cases = mean(total_cases, na.rm = TRUE), 
                              total_deaths = mean(total_deaths, na.rm = TRUE),
                              people_vaccinated = mean(people_vaccinated, na.rm = TRUE))

Avg_by_continent <- Avg_by_continent[order(Avg_by_continent$total_cases, decreasing = TRUE), ]
Avg_by_continent = Avg_by_continent[Avg_by_continent$continent != "",]
# Barplot
barplot(Avg_by_continent$total_cases, names.arg = Avg_by_continent$continent, 
        xlab = "Average Total Cases", ylab = "", 
        main = "Average Total Cases by Continent",
        horiz = TRUE, las = 1,, cex.names = 0.8)

barplot(Avg_by_continent$total_deaths, names.arg = Avg_by_continent$continent, 
        xlab = "Average Total Deaths", ylab = "", 
        main = "Average Total Deaths by Continent",
        horiz = TRUE, las = 1,, cex.names = 0.8)

barplot(Avg_by_continent$people_vaccinated, names.arg = Avg_by_continent$continent, 
        xlab = "Vaccinations", ylab = "", 
        main = "Vaccinations",
        horiz = TRUE, las = 1,, cex.names = 0.8)



```

```{r}
continents = c("Asia","Europe","Africa","Oceania","North America","South America")
# Filter the data for the desired continents
filtered_data <- df[df$location %in% continents, c("location", "total_cases")]
filtered_data1 <- df[df$continent %in% continents, c("location", "total_cases")]

df$continent %in% continents
df$continent %in% continents

```



###Countries

